// Bilingual copy — JA + EN
window.COPY = {
  ja: {
    nav: {
      how: "使い方",
      pricing: "料金",
      dashboard: "マイページ",
      install: "Chromeに無料で追加",
    },
    hero: {
      eyebrow: "Chrome × Notion × Gemini AI",
      h1Pre: "クリックするだけで、",
      h1Em: "操作マニュアル",
      h1Post: "が完成する。",
      lede: "スクショ・AI説明文をまとめて自動生成して、Notionへ保存。手順書1本が、5分で仕上がります。",
      ctaPrimary: "Chromeに追加する",
      ctaSecondary: "デモを見る",
      trust: ["無料プランあり", "クレジットカード不要", "14日間無料トライアル"],
      stage: {
        urlHost: "app.example.com",
        urlPath: "/dashboard",
        ext: "Manual Maker",
        side: ["ホーム", "ダッシュボード", "メンバー", "請求", "設定"],
        sideSection: "ワークスペース",
        statTitles: ["MRR", "アクティブ", "解約率"],
        steps: [
          "ダッシュボードを開く",
          "設定アイコンをクリック",
          "「保存」ボタンを押す",
        ],
        stepsAI: [
          "ブラウザで管理画面を開きます。",
          "右上の歯車アイコンをクリックします。",
          "「保存」ボタンを押して完了します。",
        ],
        notionTitle: "操作マニュアル — 設定変更",
        notionMeta: "notion.so / Manual Maker · 自動生成",
        replay: "リプレイ",
        capturing: "キャプチャ中...",
        saved: "Notionに保存済み",
      },
      stats: [
        { v: "5", suf: "min", l: "1本あたりの作成時間" },
        { v: "10", suf: "×", l: "従来比のスピード" },
        { v: "0", suf: "¥〜", l: "無料プランから" },
      ],
    },
    problem: {
      tag: "Problem",
      h2: "マニュアル作成の「当たり前」を、見直しませんか。",
      lede: "スクショを撮って、マーキングして、Notionに貼って、番号を直して。本来の業務に戻れない、その時間。",
      cells: [
        { x: "01", t: "スクショを撮るたび、画像編集ツールで矢印を手描きしている。" },
        { x: "02", t: "手順書1本に1時間以上かかっている。" },
        { x: "03", t: "手順が変わるたび、最初から作り直している。" },
        { x: "04", t: "保存場所がバラバラで、誰も見つけられない。" },
      ],
    },
    how: {
      tag: "How it works",
      h2: "3ステップで、5分以内。",
      lede: "拡張機能を入れて、クリックして、保存する。それだけ。",
      steps: [
        { n: "Step 01", t: "拡張機能を起動", d: "Chromeツールバーのアイコンをクリック。Googleアカウントでサインインすれば、すぐ使えます。" },
        { n: "Step 02", t: "手順をクリックするだけ", d: "「記録開始」を押して、説明したい箇所を順番にクリック。スクショと番号付き矢印が自動生成されます。" },
        { n: "Step 03", t: "Notionへワンクリック保存", d: "「Notionへ保存」を押すだけ。AI説明文付きの画像ブロックがページに自動追加されます。" },
      ],
      cta: "詳しい使い方を見る",
    },
    ba: {
      tag: "Before / After",
      h2: "1時間の作業が、5分に。",
      before: {
        label: "BEFORE",
        time: "60分以上",
        items: [
          "スクショ → 画像編集 → 矢印を手描き",
          "各ステップのテキストを手で入力",
          "画像をドラッグでNotionへ",
          "見出しと番号を手動で整える",
          "完成まで1時間以上",
        ],
      },
      after: {
        label: "AFTER",
        time: "5分以内",
        items: [
          "クリックでスクショ＋矢印を自動生成",
          "AIが説明文を自動で書き起こし",
          "ワンクリックでNotionへ一括保存",
          "レイアウトと番号は自動で整列",
          "完成まで5分以内",
        ],
      },
    },
    feat: {
      tag: "Features",
      h2: "必要なものが、すべて揃っている。",
      lede: "撮る、書く、保存する。マニュアル作成のすべてを、ひとつの拡張機能で。",
      items: [
        { size: "large", t: "スクショ＋赤丸を自動付与", d: "クリックした位置に番号付きの赤丸が自動で付きます。手で矢印を描く手間が省けます。", visual: "shot" },
        { size: "med", t: "AIが説明文の下書きを生成", d: "Gemini AI が各ステップの操作内容から、説明文の下書きを作成します。必要に応じて編集できます。", visual: "ai" },
        { size: "sm", t: "Notionへ直接保存", d: "OAuth連携でワンクリック保存。", visual: "notion" },
        { size: "sm", t: "PDFエクスポート", d: "社内共有・印刷にも対応。", visual: "pdf" },
        { size: "sm", t: "PII自動マスキング", d: "個人情報を検出してぼかします。", visual: "mask" },
        { size: "med", t: "データはあなたのNotionに", d: "画像は弊社サーバーを経由せず、あなたのワークスペースに直接保存されます。", visual: "lock" },
      ],
    },
    pricing: {
      tag: "Pricing",
      h2: "シンプルな料金プラン。",
      lede: "まずは無料で試して、必要に応じてアップグレード。日割り計算でいつでも変更できます。",
      plans: [
        {
          name: "Free", price: "¥0", per: "永久無料", desc: "個人で使い始めるのに十分。",
          features: ["スクショ 20枚 / 月", "Notion 連携", "番号付き矢印アノテーション", "ウォーターマーク付き"],
          cta: "Chromeに追加する", featured: false,
        },
        {
          name: "Standard", price: "¥500", per: "/ 月", desc: "本格的に使うチーム向け。",
          features: ["スクショ 無制限", "AI 生成 100回 / 月", "PDF出力", "ウォーターマークなし"],
          cta: "14日間無料で始める", featured: true, ribbon: "おすすめ",
        },
        {
          name: "Pro", price: "¥1,200", per: "/ 月", desc: "複数ワークスペースを横断する組織向け。",
          features: ["スクショ 無制限", "AI 生成 500回 / 月", "Notion ワークスペース 3つ", "ウォーターマークなし"],
          cta: "アップグレード", featured: false,
        },
      ],
      foot: "14日間無料トライアル · いつでもキャンセル可能",
    },
    faq: {
      tag: "FAQ",
      h2: "よくある質問",
      items: [
        { q: "無料プランでどこまで使えますか？", a: "スクショ20枚/月・Notion保存・番号付き矢印アノテーションが使えます。AI説明文の自動生成は、Standard以上のプランに含まれます。" },
        { q: "Notionのどのプランが必要ですか？", a: "Notionの無料プランで連携できます。ページへの書き込み権限さえあれば、追加の費用はかかりません。" },
        { q: "スクショはどこに保存されますか？", a: "画像は直接あなたのNotionページへ保存されます。弊社サーバーへのアップロードはなく、データはあなたのWorkspaceにのみ存在します。" },
        { q: "プランはいつでも変更できますか？", a: "はい。アップグレード・ダウングレードはいつでも可能で、日割り計算でお支払いいただきます。" },
        { q: "法人・チームでの利用はできますか？", a: "Teamプラン（¥2,980/月・5席〜）をご用意しています。詳細はお問い合わせください。" },
      ],
    },
    final: {
      h2: "今日から、マニュアルを書く時間を取り戻す。",
      lede: "月20スクショまで永久無料。クレジットカード不要で、すぐに試せます。",
      ctaPrimary: "Chromeに無料で追加",
      ctaSecondary: "料金を見る",
      foot: "STANDARD PLAN — 14 DAYS FREE TRIAL",
    },
    footer: {
      desc: "クリックするだけで、操作マニュアルを自動生成。",
      links: ["プライバシーポリシー", "利用規約", "お問い合わせ"],
      copy: "© 2025 Notion Manual Maker",
    },
  },

  en: {
    nav: {
      how: "How it works",
      pricing: "Pricing",
      dashboard: "Dashboard",
      install: "Add to Chrome — Free",
    },
    hero: {
      eyebrow: "Chrome × Notion × Gemini AI",
      h1Pre: "Click your way to a ",
      h1Em: "finished manual",
      h1Post: ".",
      lede: "Auto-generate screenshots, arrow annotations, and AI captions — saved straight to Notion. A how-to that used to take an hour, done in five minutes.",
      ctaPrimary: "Add to Chrome",
      ctaSecondary: "Watch the demo",
      trust: ["Free plan", "No credit card", "14-day free trial"],
      stage: {
        urlHost: "app.example.com",
        urlPath: "/dashboard",
        ext: "Manual Maker",
        side: ["Home", "Dashboard", "Members", "Billing", "Settings"],
        sideSection: "Workspace",
        statTitles: ["MRR", "Active", "Churn"],
        steps: [
          "Open the dashboard",
          "Click the settings icon",
          "Press ‘Save’",
        ],
        stepsAI: [
          "Open the admin page in your browser.",
          "Click the gear icon at the top right.",
          "Press the ‘Save’ button to finish.",
        ],
        notionTitle: "How-to — Update settings",
        notionMeta: "notion.so / Manual Maker · auto-generated",
        replay: "Replay",
        capturing: "Capturing…",
        saved: "Saved to Notion",
      },
      stats: [
        { v: "5", suf: "min", l: "Average time per manual" },
        { v: "10", suf: "×", l: "Faster than the old way" },
        { v: "0", suf: "$+", l: "Starts at free, forever" },
      ],
    },
    problem: {
      tag: "Problem",
      h2: "The everyday tax of writing manuals.",
      lede: "Screenshot. Edit. Drop into Notion. Renumber. The interruptions add up faster than the document.",
      cells: [
        { x: "01", t: "Hand-drawing arrows on every screenshot in an image editor." },
        { x: "02", t: "Spending an hour on a single how-to document." },
        { x: "03", t: "Rebuilding the whole thing every time the UI changes." },
        { x: "04", t: "Files scattered across folders — nobody can find them." },
      ],
    },
    how: {
      tag: "How it works",
      h2: "Three steps. Five minutes.",
      lede: "Install, click, save. That’s the whole workflow.",
      steps: [
        { n: "Step 01", t: "Launch the extension", d: "Click the icon in Chrome’s toolbar. Sign in with Google and you’re set." },
        { n: "Step 02", t: "Click through your steps", d: "Hit ‘Record’, then click each thing you want to show. Screenshots and numbered arrows are generated automatically." },
        { n: "Step 03", t: "One-click to Notion", d: "Press ‘Save to Notion’. Image blocks with AI-written captions land on your page instantly." },
      ],
      cta: "See the full walkthrough",
    },
    ba: {
      tag: "Before / After",
      h2: "An hour of work, in five minutes.",
      before: {
        label: "BEFORE",
        time: "60+ min",
        items: [
          "Screenshot → image editor → hand-drawn arrows",
          "Type out the description for every step",
          "Drag images into Notion one by one",
          "Manually fix headings and numbering",
          "Over an hour to ship",
        ],
      },
      after: {
        label: "AFTER",
        time: "Under 5 min",
        items: [
          "One click — screenshot and arrow auto-generated",
          "AI writes the captions for you",
          "One click to push everything to Notion",
          "Layout and numbering align themselves",
          "Done in under five minutes",
        ],
      },
    },
    feat: {
      tag: "Features",
      h2: "Everything you need, in one extension.",
      lede: "Capture, caption, save. Manual-making, end to end.",
      items: [
        { size: "large", t: "Auto screenshots with red circles", d: "A numbered red circle is added at each click position, so you can skip drawing arrows by hand.", visual: "shot" },
        { size: "med", t: "AI-drafted captions", d: "Gemini drafts a short description for each step. Edit any line you want to refine.", visual: "ai" },
        { size: "sm", t: "Direct to Notion", d: "OAuth-connected, one-click save.", visual: "notion" },
        { size: "sm", t: "PDF export", d: "Share or print without re-formatting.", visual: "pdf" },
        { size: "sm", t: "PII auto-masking", d: "Detects and blurs personal info.", visual: "mask" },
        { size: "med", t: "Your data, your Notion", d: "Images live only in your workspace — never on our servers.", visual: "lock" },
      ],
    },
    pricing: {
      tag: "Pricing",
      h2: "Honest, simple pricing.",
      lede: "Try it free, upgrade when you need to. Pro-rated, change anytime.",
      plans: [
        {
          name: "Free", price: "$0", per: "forever", desc: "Plenty for solo experimentation.",
          features: ["20 screenshots / month", "Notion connector", "Numbered arrow annotations", "Includes watermark"],
          cta: "Add to Chrome", featured: false,
        },
        {
          name: "Standard", price: "$5", per: "/ month", desc: "For teams that ship docs daily.",
          features: ["Unlimited screenshots", "100 AI captions / month", "PDF export", "No watermark"],
          cta: "Start 14-day trial", featured: true, ribbon: "Most popular",
        },
        {
          name: "Pro", price: "$12", per: "/ month", desc: "Multi-workspace organisations.",
          features: ["Unlimited screenshots", "500 AI captions / month", "3 Notion workspaces", "No watermark"],
          cta: "Upgrade", featured: false,
        },
      ],
      foot: "14-day free trial · cancel anytime",
    },
    faq: {
      tag: "FAQ",
      h2: "Frequently asked",
      items: [
        { q: "What does the free plan include?", a: "20 screenshots per month, Notion saving, and numbered arrow annotations. AI-generated captions are part of Standard and above." },
        { q: "Which Notion plan do I need?", a: "Any plan, including the free one. As long as the connected user can write to your page, you’re good." },
        { q: "Where are my screenshots stored?", a: "Directly in your Notion page. We don’t upload them to our servers — your data stays in your workspace." },
        { q: "Can I change plans whenever?", a: "Yes — upgrades and downgrades are pro-rated and take effect immediately." },
        { q: "Is there a team plan?", a: "Yes. The Team plan starts at $29/month for 5 seats. Reach out for details." },
      ],
    },
    final: {
      h2: "Get your manual-writing time back, today.",
      lede: "Free for up to 20 screenshots a month. No credit card required.",
      ctaPrimary: "Add to Chrome — Free",
      ctaSecondary: "See pricing",
      foot: "STANDARD PLAN — 14 DAYS FREE TRIAL",
    },
    footer: {
      desc: "Click your way to a finished manual.",
      links: ["Privacy", "Terms", "Contact"],
      copy: "© 2025 Notion Manual Maker",
    },
  },
};
